version: '3'

services:
  znn:
    build: .
    ports:
      - 4000:4000
    environment:
      PORT: 4000
    depends_on: 
      - db
  db:
    image: mysql:5.5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: znn_data 
      MYSQL_USER: znn
      MYSQL_PASSWORD: znn_pass
