version: '3.7'

services:
  bbz-text:
    image: bbz:text
    ports:
      - 4000:4000
    environment:
      PGPORT: 5432
      PGDATABASE: bbz
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
    depends_on:
      - db
  bbz-low:
    image: cmendes/bbz:low
    ports:
      - 4001:4000
    environment:
      PGPORT: 5432
      PGDATABASE: bbz
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
    depends_on:
      - db
  bbz-high:
    image: cmendes/bbz:high
    ports:
      - 4002:4000
    environment:
      PGPORT: 5432
      PGDATABASE: bbz
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      POSTGRES_DB: bbz
      POSTGRES_PASSWORD: postgres
  locust:
    image: 'grubykarol/locust:0.13.5-python3.8-alpine3.11'
    container_name: locust
    hostname: locust
    ports:
     - '8089:8089'
    environment:
      ATTACKED_HOST: http://bbz-text:8089
      LOCUST_MODE: standalone
      NO_PROXY: standalone
      TASK_DELAY_FROM: 5
      TASK_DELAY_TO: 30
      QUIET_MODE: '${QUIET_MODE:-false}'
      LOCUST_OPTS: '--web-port 8089'
    volumes:
      - ./test-scripts:/locust
